/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei';
import * as THREE from 'three';
import { Group } from 'three';

export default function ScenePlugs2({ shouldPlay }: { shouldPlay: boolean }) {
    const group = useRef<Group>(null);
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    const { nodes, materials, animations } = useGLTF('/kocke002.glb');
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        if (shouldPlay) {
            Object.values(actions).forEach((animation) => {
                if (animation) {
                    animation.timeScale = 1;
                    animation.loop = THREE.LoopPingPong;
                    animation.play();
                }
            });
        } else {
            Object.values(actions).forEach((animation) => {
                if (animation) {
                    animation.stop();
                }
            });
        }
    }, [actions, shouldPlay]);

    return (
        <group ref={group} dispose={null}>
            <group name="Scene">
                <group name="camera1" position={[0, 0.01, -2.37]} rotation={[-0.01, 0, 0]} scale={1}>
                    <PerspectiveCamera
                        name="camera1"
                        makeDefault={true}
                        far={1000}
                        near={0.01}
                        zoom={0.6}
                        position={[0, 10, 0]}
                        fov={20}
                    />
                </group>

                <mesh
                    name="pasted__pUT_ULT_003_UV1_P1"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P1.geometry}
                    material={materials.aiStandardSurface1}
                    position={[-0.26, 1.97, -0.19]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P3"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P3.geometry}
                    material={materials.aiStandardSurface1}
                    position={[-0.08, 1.97, -0.19]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P5"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P5.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.24, 2.05, -0.19]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P6"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P6.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.1, 1.97, -0.02]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P11"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P11.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.1, 2.1, 0.15]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P13"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P13.geometry}
                    material={materials.aiStandardSurface1}
                    position={[-0.08, 2.12, 0.15]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P15"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P15.geometry}
                    material={materials.aiStandardSurface1}
                    position={[-0.26, 2.26, 0.15]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P17"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P17.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.25, 1.87, -0.19]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P21"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P21.geometry}
                    material={materials.aiStandardSurface1}
                    position={[-0.26, 1.76, -0.02]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P25"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P25.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.1, 1.81, -0.02]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
                <mesh
                    name="pasted__pUT_ULT_003_UV1_P28"
                    geometry={nodes.pasted__pUT_ULT_003_UV1_P28.geometry}
                    material={materials.aiStandardSurface1}
                    position={[0.24, 1.73, 0.15]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.02}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/kocke002.glb');
