/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei';
import { Group } from 'three';
import * as THREE from 'three';

export default function Switch2({ shouldPlay }: { shouldPlay: boolean }) {
    const group = useRef<Group>(null);
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    const { nodes, materials, animations } = useGLTF('/Blend-sim003-box01.glb');
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        if (shouldPlay) {
            Object.values(actions).forEach((animation) => {
                if (animation) {
                    animation.timeScale = 1;
                    animation.loop = THREE.LoopPingPong;
                    animation.play();
                }
            });
        } else {
            Object.values(actions).forEach((animation) => {
                if (animation) {
                    animation.stop();
                }
            });
        }
    }, [actions, shouldPlay]);
    return (
        <group ref={group} dispose={null}>
            <group name="Scene">
                <pointLight
                    name="Point002"
                    intensity={0.5}
                    decay={2}
                    color="#ffead0"
                    position={[0, 5.27, 3.86]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                {/*<directionalLight*/}
                {/*    name="Sun"*/}
                {/*    intensity={0.1}*/}
                {/*    color="#ffdec0"*/}
                {/*    position={[0, 2.85, 0]}*/}
                {/*    rotation={[-1.33, 0.06, -0.01]}*/}
                {/*>*/}
                {/*    <group position={[0, 0, -1]} />*/}
                {/*</directionalLight>*/}
                {/*<pointLight*/}
                {/*    name="Point001"*/}
                {/*    intensity={35}*/}
                {/*    decay={2}*/}
                {/*    color="#ffead0"*/}
                {/*    position={[0, -1.44, 3.86]}*/}
                {/*    rotation={[-Math.PI / 2, 0, 0]}*/}
                {/*/>*/}
                <PerspectiveCamera
                    name="V2_bake_fbxcamera1"
                    makeDefault={true}
                    far={100}
                    near={1}
                    fov={50}
                    zoom={1}
                    position={[0, 2, 3.26]}
                    rotation={[0.07, 0, 0]}
                    scale={0.11}
                />
                <mesh
                    name="box02"
                    geometry={nodes.box02.geometry}
                    material={materials['V2_bake_fbx:aiStandardSurface1.005']}
                    position={[0, 2.95, 0.75]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.03}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/Blend-sim003-box01.glb');
